### PR TITLE
MNT: blark v0.3.0 compatibility

### LINKED ISSUE #113: Lark 1.0 compatibility
Some backward-incompatible changes and/or bugfixes that will need to be addressed:
* Lark parsers which use earley/dynamic do not support `lexer_callbacks`; apparently these have been failing silently :(
   - dbtemplate, snl, streamdevice will need to disable the callback and find a workaround
* Check grammars for maybe_optional; the default was changed
* Check rule priority values
* Pin to lark >1.0
* Change `lark-parser` pip requirement to just `lark`
* 
Ref https://github.com/lark-parser/lark/releases/tag/1.0.0

### LINKED ISSUE #114: pytmc plugin: blark compatibility
With the advent of Python dataclasses for PLC code elements as in https://github.com/klauer/blark/pull/9, whatrecord's pytmc plugin will need some adjustment to pick out data types and such.

### PR DESCRIPTION
**Pull request by klauer**
## Description
* Removes lark pin (local testing indicates it's fine with v1.0 now)
* Fixes compatibility with blark v0.3.0, which is massively different from previous releases

## Motivation and Context
* Closes #113
* Closes #114 
* And the pytmc plugin is neat

## How Has This Been Tested?
* Locally, more testing is probably a good idea
* This is not covered in the test suite, which is quite bad, even if this is an optional extension to whatrecord

## Where Has This Been Documented?
PR text and issue

### CODE REVIEW

**Comment by klauer** [comment]
(Mostly a rubber-stamp request, @ZLLentz ; there's no way you could properly review this without digging into blark/whatrecord for an hour...)

**Comment by klauer** [comment]
(Mostly a rubber-stamp request, @ZLLentz ; there's no way you could properly review this without digging into blark/whatrecord for an hour...)

**Comment by ZLLentz** [comment]
I'll read it through to get an idea of what kind of stuff goes into this

**Review by ZLLentz — APPROVED** [review]
You are absolutely right, this would require some digging to properly review and follow the program flow.
Good job on eliminating so many lines of code though!

**Comment by klauer** [comment]
Thanks, @ZLLentz 😁

**Pull request merged**
