### PR TITLE
BLD: use maintained lark conda-forge package

### LINKED ISSUE #179: conda-recipe references defunct lark-parser version
On conda-forge, `lark-parser` has an ancient version of `lark` in it, whereas `lark` has the latest:
https://github.com/pcdshub/whatrecord/blob/71200d993a7684efaa4788fdefc072e20e5740a9/conda-recipe/meta.yaml#L29

We fixed this on conda-forge, but we need to adjust the recipe here as well.

Reference:
https://anaconda.org/conda-forge/lark-parser/files
vs
https://anaconda.org/conda-forge/lark/files

### PR DESCRIPTION
**Pull request by klauer**
## Description
Closes #179

### CODE REVIEW

**Comment by klauer** [comment]
Conda jobs now failing due to some asyncio stuff which passes on the pip-based jobs.
(pytest-asyncio plugin version may be suspect? Need to compare the environments)

**Comment by klauer** [comment]
conda: `plugins: cov-4.1.0, asyncio-0.22.0`
pip: `plugins: cov-4.1.0, asyncio-0.21.1`

**Comment by klauer** [comment]
OK, bad version of pytest-asyncio is causing this: https://github.com/conda-forge/pytest-asyncio-feedstock/issues/35

**Review by tangkong — APPROVED** [review]
LGTM

**Pull request merged**
